version: "3"

services:
    cafecito:
        container_name: caps
        image: caps
        restart: always
        build: .
        environment:
            NODE_ENV: production,
            MONGO_DB: mongodb+srv://capsDB:uVoC8ECze76xJ9QN@cluster0-onwp0.mongodb.net/test?retryWrites=true&w=majority
            SECRET_TOKEN: my_secret_token
            URL_BASE: http://localhost:4000
        ports:
            - 4000:4000
        logging:
            options:
                max-size: 50m
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        ports:
            - "27017:27017"
